In [27]:
from social_ES import INE
import pprint
wd = "/home/gmor/Nextcloud2/Beegroup/data/social_ES"

# Household Income Distribution
The [Annual Household Income Distribution dataset](https://www.ine.es/dyngs/INEbase/en/operacion.htm?c=Estadistica_C&cid=1254736177088&menu=ultiDatos&idp=1254735976608)  is an extensive dataset derived from administrative records, offering detailed insights into income distribution across households in Spain. It presents the income levels and their distribution, segmented by key demographic variables. The dataset provides a granular territorial breakdown, covering municipalities, districts, and census sections throughout the country, thus enabling in-depth analysis at various administrative levels.

In [ ]:
atlas_df = INE.HouseholdIncomeDistributionAtlas(wd=wd)

These are the geographical levels available:

In [34]:
pprint.pp(list(atlas_df.keys()))

['Municipality', 'Districts', 'Sections']

An example of the results for the municipality of Barcelona at census tract level is the following:

In [15]:
atlas_df["Sections"][atlas_df["Sections"]["Municipality code"]=="08019"]

,Municipality name,Municipality code,District code,Section code,Year,Average household income,Average household net income,Average income by unit of consumption,Average net income per person,Average per person gross income,...,Income distribution P80/P20,Average age of the population,Percentage of Spanish population,Percentage of the population over the age of 65,Percentage of the population under the age of 18,Population,Porcentaje de hogares unipersonales,Tama√±o medio del hogar,Country code,Province code
56391,Barcelona,08019,01,001,2015,28573.0,24471.0,13553.0,9310.0,10871.0,...,3.0,40.5,53.8,16.2,12.6,1263.0,36.9,2.5,ES,08
56392,Barcelona,08019,01,001,2016,29324.0,24839.0,14541.0,9977.0,11779.0,...,2.9,41.3,55.5,17.4,12.8,1164.0,36.3,2.4,ES,08
56393,Barcelona,08019,01,001,2017,31150.0,26107.0,15475.0,10614.0,12664.0,...,3.0,40.9,56.7,16.6,12.8,1196.0,39.8,2.3,ES,08
56394,Barcelona,08019,01,001,2018,31967.0,26743.0,14983.0,10366.0,12391.0,...,3.3,40.7,53.4,16.4,11.7,1205.0,42.0,2.3,ES,08
56395,Barcelona,08019,01,001,2019,32635.0,27387.0,16074.0,10928.0,13022.0,...,3.3,41.0,53.7,17.1,11.7,1208.0,40.0,2.4,ES,08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65002,Barcelona,08019,10,237,2018,31731.0,27411.0,17712.0,12274.0,14209.0,...,2.3,47.8,86.3,27.5,14.2,850.0,35.6,2.2,ES,08
65003,Barcelona,08019,10,237,2019,33429.0,28184.0,18132.0,12641.0,14993.0,...,2.5,47.1,83.8,25.1,13.7,903.0,37.0,2.2,ES,08
65004,Barcelona,08019,10,237,2020,34142.0,29058.0,18307.0,12869.0,15120.0,...,2.5,46.1,84.3,22.9,14.1,920.0,36.5,2.2,ES,08
65005,Barcelona,08019,10,237,2021,35946.0,30416.0,19203.0,13443.0,15888.0,...,2.4,46.1,83.7,23.2,14.7,897.0,36.1,2.2,ES,08
65006,Barcelona,08019,10,237,2022,36788.0,30852.0,19778.0,13855.0,16521.0,...,2.6,45.4,82.0,22.9,15.2,888.0,38.6,2.2,ES,08

The columns available in this dataset are:

In [39]:
pprint.pp(list(atlas_df['Sections'].columns), width=400)

['Municipality name',
 'Municipality code',
 'District code',
 'Section code',
 'Year',
 'Average household income',
 'Average household net income',
 'Average income by unit of consumption',
 'Average net income per person',
 'Average per person gross income',
 'Median income by unit of consumption',
 'Fuente de ingreso: otras prestaciones',
 'Fuente de ingreso: otros ingresos',
 'Fuente de ingreso: pensiones',
 'Fuente de ingreso: prestaciones por desempleo',
 'Fuente de ingreso: salario',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Males',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Females',
 'Percentage of the population with income per consumption unit of under 5,000 euros ',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Males',
 'Percentage of the population with income per consumption unit of under 7,500 euros ',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Females',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Males',
 'Percentage of the population with income per consumption unit of under 10,000 euros ',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Females',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Males ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Males ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Females ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Females ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Males ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Females ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Males ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Females ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Males ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Males ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Females ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Females ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Males ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Females ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Males ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Females ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Females ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Males ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Males ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Females ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Males ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Females ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Females ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Sex:Males ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 5,000 euros  ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Males ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Females ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Males ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 7,500 euros  ~ Sex:Females ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Males ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Sex:Females ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 10,000 euros  ~ Nationality:Foreign',
 'Population with per consumption unit income above 200% of the median ~ Sex:Females',
 'Population with per consumption unit income above 200% of the median',
 'Population with per consumption unit income above 200% of the median ~ Sex:Males',
 'Population with per consumption unit income above 160% of the median ~ Sex:Females',
 'Population with per consumption unit income above 160% of the median',
 'Population with per consumption unit income above 160% of the median ~ Sex:Males',
 'Population with per consumption unit income above 140% of the median ~ Sex:Females',
 'Population with per consumption unit income above 140% of the median ~ Sex:Males',
 'Population with per consumption unit income above 140% of the median',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Males',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Males',
 'Percentage of the population with income per consumption unit of under 40% of the median ',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Females',
 'Percentage of the population with income per consumption unit of under 50% of the median ',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Males',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Females',
 'Percentage of the population with income per consumption unit of under 60% of the median ',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Females',
 'Population with per consumption unit income above 200% of the median ~ Sex:Males ~ Age:<18',
 'Population with per consumption unit income above 200% of the median ~ Sex:Females ~ Age:<18',
 'Population with per consumption unit income above 200% of the median ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Males ~ Age:>64',
 'Population with per consumption unit income above 200% of the median ~ Sex:Females ~ Age:>64',
 'Population with per consumption unit income above 200% of the median ~ Sex:Males ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Males ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Females ~ Age:>64',
 'Population with per consumption unit income above 200% of the median ~ Age:>64',
 'Population with per consumption unit income above 200% of the median ~ Sex:Females ~ Age:18-64',
 'Population with per consumption unit income above 160% of the median ~ Sex:Males ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Females ~ Age:>64',
 'Population with per consumption unit income above 160% of the median ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Age:>64',
 'Population with per consumption unit income above 160% of the median ~ Sex:Females ~ Age:<18',
 'Population with per consumption unit income above 140% of the median ~ Sex:Females ~ Age:<18',
 'Population with per consumption unit income above 200% of the median ~ Age:18-64',
 'Population with per consumption unit income above 200% of the median ~ Sex:Males ~ Age:18-64',
 'Population with per consumption unit income above 160% of the median ~ Sex:Males ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Males ~ Age:>64',
 'Population with per consumption unit income above 140% of the median ~ Sex:Males ~ Age:<18',
 'Population with per consumption unit income above 160% of the median ~ Sex:Females ~ Age:>64',
 'Population with per consumption unit income above 160% of the median ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Males ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Females ~ Age:18-64',
 'Population with per consumption unit income above 140% of the median ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Females ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Males ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Males ~ Age:18-64',
 'Population with per consumption unit income above 140% of the median ~ Sex:Females ~ Age:>64',
 'Population with per consumption unit income above 160% of the median ~ Sex:Females ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Age:>64',
 'Population with per consumption unit income above 140% of the median ~ Sex:Males ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Females ~ Age:<18',
 'Population with per consumption unit income above 140% of the median ~ Age:>64',
 'Population with per consumption unit income above 160% of the median ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Females ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Males ~ Age:<18',
 'Population with per consumption unit income above 160% of the median ~ Sex:Males ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Males ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Females ~ Age:>64',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Females ~ Age:<18',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Males ~ Age:<18',
 'Population with per consumption unit income above 140% of the median ~ Sex:Females ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Females ~ Age:18-64',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Age:<18',
 'Population with per consumption unit income above 140% of the median ~ Age:18-64',
 'Population with per consumption unit income above 140% of the median ~ Sex:Males ~ Age:18-64',
 'Population with per consumption unit income above 200% of the median ~ Sex:Females ~ Nationality:Foreign',
 'Population with per consumption unit income above 200% of the median ~ Sex:Males ~ Nationality:Foreign',
 'Population with per consumption unit income above 200% of the median ~ Nationality:Foreign',
 'Population with per consumption unit income above 160% of the median ~ Sex:Males ~ Nationality:Foreign',
 'Population with per consumption unit income above 160% of the median ~ Nationality:Foreign',
 'Population with per consumption unit income above 160% of the median ~ Sex:Females ~ Nationality:Foreign',
 'Population with per consumption unit income above 140% of the median ~ Sex:Males ~ Nationality:Foreign',
 'Population with per consumption unit income above 140% of the median ~ Nationality:Foreign',
 'Population with per consumption unit income above 140% of the median ~ Sex:Females ~ Nationality:Foreign',
 'Population with per consumption unit income above 200% of the median ~ Nationality:Spanish',
 'Population with per consumption unit income above 200% of the median ~ Sex:Females ~ Nationality:Spanish',
 'Population with per consumption unit income above 200% of the median ~ Sex:Males ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Males ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Females ~ Nationality:Spanish',
 'Population with per consumption unit income above 160% of the median ~ Sex:Females ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Males ~ Nationality:Spanish',
 'Population with per consumption unit income above 160% of the median ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Nationality:Spanish',
 'Population with per consumption unit income above 160% of the median ~ Sex:Males ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Females ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Males ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Females ~ Nationality:Spanish',
 'Population with per consumption unit income above 140% of the median ~ Sex:Females ~ Nationality:Spanish',
 'Population with per consumption unit income above 140% of the median ~ Nationality:Spanish',
 'Population with per consumption unit income above 140% of the median ~ Sex:Males ~ Nationality:Spanish',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Males ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Sex:Females ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 40% of the median  ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Females ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Sex:Males ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 50% of the median  ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Females ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Nationality:Foreign',
 'Percentage of the population with income per consumption unit of under 60% of the median  ~ Sex:Males ~ Nationality:Foreign',
 'Gini Index',
 'Income distribution P80/P20',
 'Average age of the population',
 'Percentage of Spanish population',
 'Percentage of the population over the age of 65',
 'Percentage of the population under the age of 18',
 'Population',
 'Porcentaje de hogares unipersonales',
 'Tama√±o medio del hogar',
 'Country code',
 'Province code']

# Population Census

The [Annual Population Census](https://www.ine.es/dynt3/inebase/en/index.htm?padre=11555&capsel=11100) provides detailed demographic statistics for all census sections in Spain, identified by country, province, municipality, district, and section codes, along with the reference year. It includes total population counts disaggregated by nationality, sex, birth origin, and birth country, covering both Spanish and foreign residents across multiple specific nationalities. Data also capture birthplace distribution within Spain (same municipality, province, autonomous community, or other regions) and abroad. Age structure is available in five-year intervals, further broken down by sex. The dataset offers highly granular insights into the composition and spatial distribution of the population, enabling analyses of migration patterns, gender distribution, and demographic ageing. Its fine territorial resolution supports local planning, socio-economic studies, and policy-making, particularly for municipalities, districts, and neighbourhoods.

In [ ]:
population_df = INE.PopulationCensus(wd=wd)

These are the geographical levels available:

In [40]:
pprint.pp(list(population_df.keys()))

['Municipality', 'Districts', 'Sections']

An example of the results for the municipality of Barcelona at census tract level is the following:

In [17]:
population_df["Sections"][population_df["Sections"]["Municipality code"]=="08019"]

,Country code,Province code,Municipality code,District code,Year,Section code,Population,Population ~ Nationality:Spanish,Population ~ Nationality:Foreign,Population ~ Sex:Males,...,Population ~ Sex:Females ~ Age:55-59,Population ~ Sex:Females ~ Age:60-64,Population ~ Sex:Females ~ Age:65-69,Population ~ Sex:Females ~ Age:70-74,Population ~ Sex:Females ~ Age:75-79,Population ~ Sex:Females ~ Age:80-84,Population ~ Sex:Females ~ Age:85-89,Population ~ Sex:Females ~ Age:90-94,Population ~ Sex:Females ~ Age:95-99,Population ~ Sex:Females ~ Age:>99
18748,ES,08,08019,01,2021,001,1247.0,685.0,562.0,672.0,...,31.0,14.0,23.0,23.0,23.0,16.0,11.0,6.0,2.0,0.0
18749,ES,08,08019,01,2021,002,1399.0,594.0,805.0,729.0,...,32.0,19.0,22.0,16.0,14.0,21.0,24.0,15.0,6.0,1.0
18750,ES,08,08019,01,2021,003,3484.0,1860.0,1624.0,1912.0,...,85.0,76.0,43.0,46.0,36.0,32.0,32.0,10.0,5.0,0.0
18751,ES,08,08019,01,2021,004,2846.0,1500.0,1346.0,1553.0,...,82.0,51.0,33.0,39.0,33.0,16.0,17.0,13.0,4.0,0.0
18752,ES,08,08019,01,2021,005,2364.0,1222.0,1142.0,1264.0,...,52.0,53.0,37.0,34.0,26.0,31.0,25.0,10.0,5.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30785,ES,08,08019,10,2024,143,1787.0,1384.0,403.0,838.0,...,78.0,61.0,42.0,37.0,49.0,52.0,36.0,22.0,1.0,1.0
30786,ES,08,08019,10,2024,234,1765.0,1502.0,263.0,794.0,...,61.0,93.0,111.0,90.0,48.0,37.0,15.0,11.0,5.0,3.0
30787,ES,08,08019,10,2024,235,1296.0,1063.0,233.0,603.0,...,42.0,60.0,40.0,40.0,61.0,44.0,26.0,9.0,3.0,1.0
30788,ES,08,08019,10,2024,236,1572.0,1223.0,349.0,734.0,...,54.0,51.0,26.0,42.0,86.0,67.0,50.0,23.0,4.0,0.0
30789,ES,08,08019,10,2024,237,853.0,701.0,152.0,382.0,...,34.0,20.0,20.0,14.0,28.0,24.0,33.0,13.0,4.0,0.0

The columns available in this dataset are:

In [42]:
pprint.pp(list(population_df['Sections'].columns), width=400)

['Country code',
 'Province code',
 'Municipality code',
 'District code',
 'Year',
 'Section code',
 'Population',
 'Population ~ Nationality:Spanish',
 'Population ~ Nationality:Foreign',
 'Population ~ Sex:Males',
 'Population ~ Sex:Males ~ Nationality:Spanish',
 'Population ~ Sex:Males ~ Nationality:Foreign',
 'Population ~ Sex:Females',
 'Population ~ Sex:Females ~ Nationality:Spanish',
 'Population ~ Sex:Females ~ Nationality:Foreign',
 'Population ~ Birth origin:Spain',
 'Population ~ Birth origin:Foreign country',
 'Population ~ Sex:Males ~ Birth origin:Spain',
 'Population ~ Sex:Males ~ Birth origin:Foreign country',
 'Population ~ Sex:Females ~ Birth origin:Spain',
 'Population ~ Sex:Females ~ Birth origin:Foreign country',
 'Population ~ Nationality:Espa√±a',
 'Population ~ Nationality:French',
 'Population ~ Nationality:British',
 'Population ~ Nationality:Romanian',
 'Population ~ Nationality:Ukrainian',
 'Population ~ Nationality:Other European nationalities',
 'Population ~ Nationality:Moroccan',
 'Population ~ Nationality:Other African nationalities',
 'Population ~ Nationality:Cuban',
 'Population ~ Nationality:Dominican',
 'Population ~ Nationality:Argentinian',
 'Population ~ Nationality:Bolivian',
 'Population ~ Nationality:Colombian',
 'Population ~ Nationality:Ecuadorian',
 'Population ~ Nationality:Peruvian',
 'Population ~ Nationality:Venezuelan',
 'Population ~ Nationality:Other American nationalities',
 'Population ~ Nationality:Chinese',
 'Population ~ Nationality:Other Asian nationalities',
 'Population ~ Nationality:Oceanian',
 'Population ~ Nationality:Stateless',
 'Population ~ Sex:Males ~ Nationality:Espa√±a',
 'Population ~ Sex:Males ~ Nationality:French',
 'Population ~ Sex:Males ~ Nationality:British',
 'Population ~ Sex:Males ~ Nationality:Romanian',
 'Population ~ Sex:Males ~ Nationality:Ukrainian',
 'Population ~ Sex:Males ~ Nationality:Other European nationalities',
 'Population ~ Sex:Males ~ Nationality:Moroccan',
 'Population ~ Sex:Males ~ Nationality:Other African nationalities',
 'Population ~ Sex:Males ~ Nationality:Cuban',
 'Population ~ Sex:Males ~ Nationality:Dominican',
 'Population ~ Sex:Males ~ Nationality:Argentinian',
 'Population ~ Sex:Males ~ Nationality:Bolivian',
 'Population ~ Sex:Males ~ Nationality:Colombian',
 'Population ~ Sex:Males ~ Nationality:Ecuadorian',
 'Population ~ Sex:Males ~ Nationality:Peruvian',
 'Population ~ Sex:Males ~ Nationality:Venezuelan',
 'Population ~ Sex:Males ~ Nationality:Other American nationalities',
 'Population ~ Sex:Males ~ Nationality:Chinese',
 'Population ~ Sex:Males ~ Nationality:Other Asian nationalities',
 'Population ~ Sex:Males ~ Nationality:Oceanian',
 'Population ~ Sex:Males ~ Nationality:Stateless',
 'Population ~ Sex:Females ~ Nationality:Espa√±a',
 'Population ~ Sex:Females ~ Nationality:French',
 'Population ~ Sex:Females ~ Nationality:British',
 'Population ~ Sex:Females ~ Nationality:Romanian',
 'Population ~ Sex:Females ~ Nationality:Ukrainian',
 'Population ~ Sex:Females ~ Nationality:Other European nationalities',
 'Population ~ Sex:Females ~ Nationality:Moroccan',
 'Population ~ Sex:Females ~ Nationality:Other African nationalities',
 'Population ~ Sex:Females ~ Nationality:Cuban',
 'Population ~ Sex:Females ~ Nationality:Dominican',
 'Population ~ Sex:Females ~ Nationality:Argentinian',
 'Population ~ Sex:Females ~ Nationality:Bolivian',
 'Population ~ Sex:Females ~ Nationality:Colombian',
 'Population ~ Sex:Females ~ Nationality:Ecuadorian',
 'Population ~ Sex:Females ~ Nationality:Peruvian',
 'Population ~ Sex:Females ~ Nationality:Venezuelan',
 'Population ~ Sex:Females ~ Nationality:Other American nationalities',
 'Population ~ Sex:Females ~ Nationality:Chinese',
 'Population ~ Sex:Females ~ Nationality:Other Asian nationalities',
 'Population ~ Sex:Females ~ Nationality:Oceanian',
 'Population ~ Sex:Females ~ Nationality:Stateless',
 'Population ~ Birth country:Spain',
 'Population ~ Birth country:France',
 'Population ~ Birth country:United Kingdom',
 'Population ~ Birth country:Romania',
 'Population ~ Birth country:Ukraine',
 'Population ~ Birth country:Other European countries',
 'Population ~ Birth country:Morocco',
 'Population ~ Birth country:Other African countries',
 'Population ~ Birth country:Cuba',
 'Population ~ Birth country:Dominican Republic',
 'Population ~ Birth country:Argentina',
 'Population ~ Birth country:Bolivia',
 'Population ~ Birth country:Colombia',
 'Population ~ Birth country:Ecuador',
 'Population ~ Birth country:Peru',
 'Population ~ Birth country:Venezuela',
 'Population ~ Birth country:Other American countries',
 'Population ~ Birth country:China',
 'Population ~ Birth country:Other Asian countries',
 'Population ~ Birth country:Oceania',
 'Population ~ Sex:Males ~ Birth country:Spain',
 'Population ~ Sex:Males ~ Birth country:France',
 'Population ~ Sex:Males ~ Birth country:United Kingdom',
 'Population ~ Sex:Males ~ Birth country:Romania',
 'Population ~ Sex:Males ~ Birth country:Ukraine',
 'Population ~ Sex:Males ~ Birth country:Other European countries',
 'Population ~ Sex:Males ~ Birth country:Morocco',
 'Population ~ Sex:Males ~ Birth country:Other African countries',
 'Population ~ Sex:Males ~ Birth country:Cuba',
 'Population ~ Sex:Males ~ Birth country:Dominican Republic',
 'Population ~ Sex:Males ~ Birth country:Argentina',
 'Population ~ Sex:Males ~ Birth country:Bolivia',
 'Population ~ Sex:Males ~ Birth country:Colombia',
 'Population ~ Sex:Males ~ Birth country:Ecuador',
 'Population ~ Sex:Males ~ Birth country:Peru',
 'Population ~ Sex:Males ~ Birth country:Venezuela',
 'Population ~ Sex:Males ~ Birth country:Other American countries',
 'Population ~ Sex:Males ~ Birth country:China',
 'Population ~ Sex:Males ~ Birth country:Other Asian countries',
 'Population ~ Sex:Males ~ Birth country:Oceania',
 'Population ~ Sex:Females ~ Birth country:Spain',
 'Population ~ Sex:Females ~ Birth country:France',
 'Population ~ Sex:Females ~ Birth country:United Kingdom',
 'Population ~ Sex:Females ~ Birth country:Romania',
 'Population ~ Sex:Females ~ Birth country:Ukraine',
 'Population ~ Sex:Females ~ Birth country:Other European countries',
 'Population ~ Sex:Females ~ Birth country:Morocco',
 'Population ~ Sex:Females ~ Birth country:Other African countries',
 'Population ~ Sex:Females ~ Birth country:Cuba',
 'Population ~ Sex:Females ~ Birth country:Dominican Republic',
 'Population ~ Sex:Females ~ Birth country:Argentina',
 'Population ~ Sex:Females ~ Birth country:Bolivia',
 'Population ~ Sex:Females ~ Birth country:Colombia',
 'Population ~ Sex:Females ~ Birth country:Ecuador',
 'Population ~ Sex:Females ~ Birth country:Peru',
 'Population ~ Sex:Females ~ Birth country:Venezuela',
 'Population ~ Sex:Females ~ Birth country:Other American countries',
 'Population ~ Sex:Females ~ Birth country:China',
 'Population ~ Sex:Females ~ Birth country:Other Asian countries',
 'Population ~ Sex:Females ~ Birth country:Oceania',
 'Population ~ Birth origin in Spain:Born in the same municipality',
 'Population ~ Birth origin in Spain:Born in a municipality of the same province',
 'Population ~ Birth origin in Spain:Born in a municipality of the same autonomous community',
 'Population ~ Birth origin in Spain:Born in a municipality of another autonomous community',
 'Population ~ Birth origin in Spain:Born in another country',
 'Population ~ Sex:Males ~ Birth origin in Spain:Born in the same municipality',
 'Population ~ Sex:Males ~ Birth origin in Spain:Born in a municipality of the same province',
 'Population ~ Sex:Males ~ Birth origin in Spain:Born in a municipality of the same autonomous community',
 'Population ~ Sex:Males ~ Birth origin in Spain:Born in a municipality of another autonomous community',
 'Population ~ Sex:Males ~ Birth origin in Spain:Born in another country',
 'Population ~ Sex:Females ~ Birth origin in Spain:Born in the same municipality',
 'Population ~ Sex:Females ~ Birth origin in Spain:Born in a municipality of the same province',
 'Population ~ Sex:Females ~ Birth origin in Spain:Born in a municipality of the same autonomous community',
 'Population ~ Sex:Females ~ Birth origin in Spain:Born in a municipality of another autonomous community',
 'Population ~ Sex:Females ~ Birth origin in Spain:Born in another country',
 'Population ~ Age:0-4',
 'Population ~ Age:5-9',
 'Population ~ Age:10-14',
 'Population ~ Age:15-19',
 'Population ~ Age:20-24',
 'Population ~ Age:25-29',
 'Population ~ Age:30-34',
 'Population ~ Age:35-39',
 'Population ~ Age:40-44',
 'Population ~ Age:45-49',
 'Population ~ Age:50-54',
 'Population ~ Age:55-59',
 'Population ~ Age:60-64',
 'Population ~ Age:65-69',
 'Population ~ Age:70-74',
 'Population ~ Age:75-79',
 'Population ~ Age:80-84',
 'Population ~ Age:85-89',
 'Population ~ Age:90-94',
 'Population ~ Age:95-99',
 'Population ~ Age:>99',
 'Population ~ Sex:Males ~ Age:0-4',
 'Population ~ Sex:Males ~ Age:5-9',
 'Population ~ Sex:Males ~ Age:10-14',
 'Population ~ Sex:Males ~ Age:15-19',
 'Population ~ Sex:Males ~ Age:20-24',
 'Population ~ Sex:Males ~ Age:25-29',
 'Population ~ Sex:Males ~ Age:30-34',
 'Population ~ Sex:Males ~ Age:35-39',
 'Population ~ Sex:Males ~ Age:40-44',
 'Population ~ Sex:Males ~ Age:45-49',
 'Population ~ Sex:Males ~ Age:50-54',
 'Population ~ Sex:Males ~ Age:55-59',
 'Population ~ Sex:Males ~ Age:60-64',
 'Population ~ Sex:Males ~ Age:65-69',
 'Population ~ Sex:Males ~ Age:70-74',
 'Population ~ Sex:Males ~ Age:75-79',
 'Population ~ Sex:Males ~ Age:80-84',
 'Population ~ Sex:Males ~ Age:85-89',
 'Population ~ Sex:Males ~ Age:90-94',
 'Population ~ Sex:Males ~ Age:95-99',
 'Population ~ Sex:Males ~ Age:>99',
 'Population ~ Sex:Females ~ Age:0-4',
 'Population ~ Sex:Females ~ Age:5-9',
 'Population ~ Sex:Females ~ Age:10-14',
 'Population ~ Sex:Females ~ Age:15-19',
 'Population ~ Sex:Females ~ Age:20-24',
 'Population ~ Sex:Females ~ Age:25-29',
 'Population ~ Sex:Females ~ Age:30-34',
 'Population ~ Sex:Females ~ Age:35-39',
 'Population ~ Sex:Females ~ Age:40-44',
 'Population ~ Sex:Females ~ Age:45-49',
 'Population ~ Sex:Females ~ Age:50-54',
 'Population ~ Sex:Females ~ Age:55-59',
 'Population ~ Sex:Females ~ Age:60-64',
 'Population ~ Sex:Females ~ Age:65-69',
 'Population ~ Sex:Females ~ Age:70-74',
 'Population ~ Sex:Females ~ Age:75-79',
 'Population ~ Sex:Females ~ Age:80-84',
 'Population ~ Sex:Females ~ Age:85-89',
 'Population ~ Sex:Females ~ Age:90-94',
 'Population ~ Sex:Females ~ Age:95-99',
 'Population ~ Sex:Females ~ Age:>99']

# Population Education and Employment Status Census

This [dataset](https://www.ine.es/dynt3/inebase/en/index.htm?padre=10608&capsel=10613) provides detailed information on the educational attainment and labour market situation of the population in Spain, disaggregated to the census section level and identified by country, province, municipality, district, and section codes, as well as reference year. Educational attainment is classified into four categories: primary or below, lower secondary, upper secondary and post-secondary non-tertiary, and tertiary education. Data are further broken down by sex, place of birth (Spain or abroad), and their intersections. Labour force status includes employed, unemployed, recipients of disability or retirement pensions, other inactive situations, and students. These variables are also cross-classified by sex and place of birth, enabling nuanced analysis of participation, unemployment, and education levels across different population groups. The dataset supports local and regional assessments of human capital, workforce composition, and socio-economic inequalities, making it a valuable resource for policy design, education planning, and labour market studies.

In [ ]:
population_education_and_labour_df = INE.EducationAndEmploymentCensus(wd=wd, mode="relative")

These are the geographical levels available:

In [41]:
pprint.pp(list(population_education_and_labour_df.keys()))

['Municipality', 'Districts', 'Sections']

An example of the results for the municipality of Barcelona at census tract level is the following:

In [19]:
population_education_and_labour_df["Sections"][population_education_and_labour_df["Sections"]["Municipality code"]=="08019"]

,Country code,Province code,Municipality code,District code,Year,Section code,Population ~ Sex:Males ~ Educational level:Primary education or below,Population ~ Sex:Males ~ Educational level:Lower secondary education or equivalent,Population ~ Sex:Males ~ Educational level:Upper secondary and post-secondary non-tertiary education,Population ~ Sex:Males ~ Educational level:Tertiary education,...,Population ~ Birth origin:Spain ~ Labour force status:Employed,Population ~ Birth origin:Spain ~ Labour force status:Unemployed,"Population ~ Birth origin:Spain ~ Labour force status:Recipient of disability, retirement, or early retirement pension",Population ~ Birth origin:Spain ~ Labour force status:Other inactive situation,Population ~ Birth origin:Spain ~ Labour force status:Student,Population ~ Birth origin:Extranjero ~ Labour force status:Employed,Population ~ Birth origin:Extranjero ~ Labour force status:Unemployed,"Population ~ Birth origin:Extranjero ~ Labour force status:Recipient of disability, retirement, or early retirement pension",Population ~ Birth origin:Extranjero ~ Labour force status:Other inactive situation,Population ~ Birth origin:Extranjero ~ Labour force status:Student
14009,ES,08,08019,01,2021,001,7.942238,14.350181,11.371841,21.931408,...,19.202899,2.717391,13.224638,5.978261,2.989130,23.822464,5.253623,2.445652,23.007246,1.358696
14010,ES,08,08019,01,2021,002,10.223642,13.897764,11.182109,17.172524,...,10.272873,2.648475,10.513644,5.617978,1.524880,28.892456,5.939005,3.611557,27.287319,3.691814
14011,ES,08,08019,01,2021,003,14.041340,16.571632,11.760513,13.542409,...,12.001450,3.698332,10.188542,7.034083,2.791878,26.903553,5.656273,2.320522,26.758521,2.646846
14012,ES,08,08019,01,2021,004,9.390048,14.566613,11.837881,19.020867,...,19.392713,2.753036,9.392713,5.141700,2.429150,26.396761,6.153846,2.064777,23.562753,2.712551
14013,ES,08,08019,01,2021,005,9.990347,15.009653,12.017375,16.505792,...,14.751704,4.235638,11.733204,6.183057,1.898734,24.829601,6.718598,2.775073,24.391431,2.482960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22326,ES,08,08019,10,2023,143,4.942966,14.892269,13.814956,13.624842,...,30.172966,3.779628,18.898142,10.762332,3.459321,17.104420,1.665599,1.024984,11.659193,1.473414
22327,ES,08,08019,10,2023,234,3.771213,11.816468,11.565053,17.787555,...,33.228048,2.463677,29.816804,9.222994,2.969046,12.634239,1.452937,1.137081,5.432723,1.642451
22328,ES,08,08019,10,2023,235,6.678082,12.500000,10.530822,16.010274,...,27.415144,4.003481,27.502176,11.923412,2.523934,13.054830,1.653612,1.653612,9.660574,0.609225
22329,ES,08,08019,10,2023,236,8.144476,10.410765,10.410765,16.430595,...,27.880512,2.631579,30.796586,9.815078,2.844950,14.509246,1.209104,0.995733,8.321479,0.995733
22330,ES,08,08019,10,2023,237,5.835544,10.477454,12.068966,15.384615,...,32.573727,2.278820,20.911528,10.723861,4.423592,15.817694,1.608579,2.815013,8.042895,0.804290

The columns available in this dataset are:

In [44]:
pprint.pp(list(population_education_and_labour_df['Sections'].columns), width=400)

['Country code',
 'Province code',
 'Municipality code',
 'District code',
 'Year',
 'Section code',
 'Population ~ Sex:Males ~ Educational level:Primary education or below',
 'Population ~ Sex:Males ~ Educational level:Lower secondary education or equivalent',
 'Population ~ Sex:Males ~ Educational level:Upper secondary and post-secondary non-tertiary education',
 'Population ~ Sex:Males ~ Educational level:Tertiary education',
 'Population ~ Sex:Females ~ Educational level:Primary education or below',
 'Population ~ Sex:Females ~ Educational level:Lower secondary education or equivalent',
 'Population ~ Sex:Females ~ Educational level:Upper secondary and post-secondary non-tertiary education',
 'Population ~ Sex:Females ~ Educational level:Tertiary education',
 'Population ~ Educational level:Primary education or below',
 'Population ~ Educational level:Lower secondary education or equivalent',
 'Population ~ Educational level:Upper secondary and post-secondary non-tertiary education',
 'Population ~ Educational level:Tertiary education',
 'Population ~ Birth origin:Spain ~ Educational level:Primary education or below',
 'Population ~ Birth origin:Spain ~ Educational level:Lower secondary education or equivalent',
 'Population ~ Birth origin:Spain ~ Educational level:Upper secondary and post-secondary non-tertiary education',
 'Population ~ Birth origin:Spain ~ Educational level:Tertiary education',
 'Population ~ Birth origin:Extranjero ~ Educational level:Primary education or below',
 'Population ~ Birth origin:Extranjero ~ Educational level:Lower secondary education or equivalent',
 'Population ~ Birth origin:Extranjero ~ Educational level:Upper secondary and post-secondary non-tertiary education',
 'Population ~ Birth origin:Extranjero ~ Educational level:Tertiary education',
 'Population ~ Labour force status:Employed',
 'Population ~ Labour force status:Unemployed',
 'Population ~ Labour force status:Recipient of disability, retirement, or early retirement pension',
 'Population ~ Labour force status:Other inactive situation',
 'Population ~ Labour force status:Student',
 'Population ~ Sex:Males ~ Labour force status:Employed',
 'Population ~ Sex:Males ~ Labour force status:Unemployed',
 'Population ~ Sex:Males ~ Labour force status:Recipient of disability, retirement, or early retirement pension',
 'Population ~ Sex:Males ~ Labour force status:Other inactive situation',
 'Population ~ Sex:Males ~ Labour force status:Student',
 'Population ~ Sex:Females ~ Labour force status:Employed',
 'Population ~ Sex:Females ~ Labour force status:Unemployed',
 'Population ~ Sex:Females ~ Labour force status:Recipient of disability, retirement, or early retirement pension',
 'Population ~ Sex:Females ~ Labour force status:Other inactive situation',
 'Population ~ Sex:Females ~ Labour force status:Student',
 'Population ~ Birth origin:Spain ~ Labour force status:Employed',
 'Population ~ Birth origin:Spain ~ Labour force status:Unemployed',
 'Population ~ Birth origin:Spain ~ Labour force status:Recipient of disability, retirement, or early retirement pension',
 'Population ~ Birth origin:Spain ~ Labour force status:Other inactive situation',
 'Population ~ Birth origin:Spain ~ Labour force status:Student',
 'Population ~ Birth origin:Extranjero ~ Labour force status:Employed',
 'Population ~ Birth origin:Extranjero ~ Labour force status:Unemployed',
 'Population ~ Birth origin:Extranjero ~ Labour force status:Recipient of disability, retirement, or early retirement pension',
 'Population ~ Birth origin:Extranjero ~ Labour force status:Other inactive situation',
 'Population ~ Birth origin:Extranjero ~ Labour force status:Student']

# Consumer price index - 2015 Base

This [dataset](https://www.ine.es/dyngs/INEbase/en/operacion.htm?c=Estadistica_C&cid=1254736176802&menu=ultiDatos&idp=1254735976607) provides monthly Consumer Price Index values for Spain, referenced to the 2015 base year and broken down by detailed consumption classes following international COICOP classification. It includes price indices for food and beverages, tobacco, clothing, housing-related costs (including rent, electricity, gas, and water), household goods and services, health, transport, communications, recreation, education, restaurants, hotels, personal care, insurance, and other services. Each record is identified by country code, year, and month, enabling temporal analysis of inflation trends. The dataset also contains the general CPI, allowing for both overall and sector-specific inflation monitoring. Its fine-grained classification supports in-depth economic analysis, cost-of-living studies, and policy evaluation at both national and sectoral levels.

In [ ]:
cpi_df = INE.ConsumerPriceIndex(wd=wd)

These are the geographical levels available:

In [45]:
pprint.pp(list(cpi_df.keys()))

['National']

An example of the results is the following:

In [46]:
cpi_df['National']

,Country code,Year,Month,CPI 2015 base ~ Class:0111 Bread and cereals,CPI 2015 base ~ Class:0112 Meat,CPI 2015 base ~ Class:0113 Fish and seafood,"CPI 2015 base ~ Class:0114 Milk, cheese and eggs",CPI 2015 base ~ Class:0115 Oils and fats,CPI 2015 base ~ Class:0116 Fruits,CPI 2015 base ~ Class:0117 Pulses and vegetables,...,"CPI 2015 base ~ Class:1231 Jewellery, costume jewellery and watches",CPI 2015 base ~ Class:1232 Other personal effects,CPI 2015 base ~ Class:1240 Social protection,CPI 2015 base ~ Class:1252 Insurance related to housing,CPI 2015 base ~ Class:1253 Health-related insurance,CPI 2015 base ~ Class:1254 Transport related insurance,CPI 2015 base ~ Class:1255 Other insurance,CPI 2015 base ~ Class:1262 Other financial services,CPI 2015 base ~ Class:1270 Other services,CPI 2015 base ~ Class:General
0,ES,1997,1,63.36,67.67,62.61,70.30,78.52,52.99,52.43,...,37.62,91.28,NaN,47.56,NaN,59.73,NaN,49.95,60.99,65.77
1,ES,1997,2,63.55,67.14,60.46,70.51,72.80,53.10,53.02,...,37.66,91.28,NaN,48.54,NaN,59.85,NaN,50.49,61.41,65.71
2,ES,1997,3,63.68,66.87,59.65,70.44,67.87,53.15,52.43,...,37.69,91.37,NaN,48.58,NaN,59.85,NaN,53.04,61.70,65.77
3,ES,1997,4,63.74,66.81,59.30,70.44,65.14,52.88,52.96,...,37.99,91.91,NaN,48.72,NaN,59.79,NaN,53.04,61.82,65.77
4,ES,1997,5,63.61,67.94,59.13,70.16,63.02,52.18,53.02,...,38.10,92.00,NaN,49.05,NaN,59.85,NaN,54.95,61.88,65.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,ES,2025,1,134.67,137.10,147.48,136.90,185.15,148.84,156.54,...,159.23,101.64,132.00,NaN,177.47,130.37,142.29,111.67,109.51,124.31
337,ES,2025,2,134.98,137.72,145.79,136.81,172.16,155.10,156.46,...,161.89,102.03,132.96,NaN,184.71,130.37,145.30,111.67,110.03,124.80
338,ES,2025,3,133.75,138.28,143.73,138.45,164.78,161.59,156.82,...,165.65,103.21,133.45,NaN,185.68,130.37,145.30,111.67,110.28,125.66
339,ES,2025,4,133.76,139.19,143.66,139.85,157.57,162.85,158.41,...,168.64,105.01,133.88,NaN,185.68,130.37,145.30,111.67,110.48,126.44
340,ES,2025,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The columns available in this dataset are:

In [47]:
pprint.pp(list(cpi_df['National'].columns), width=400)

['Country code',
 'Year',
 'Month',
 'CPI 2015 base ~ Class:0111 Bread and cereals',
 'CPI 2015 base ~ Class:0112 Meat',
 'CPI 2015 base ~ Class:0113 Fish and seafood',
 'CPI 2015 base ~ Class:0114 Milk, cheese and eggs',
 'CPI 2015 base ~ Class:0115 Oils and fats',
 'CPI 2015 base ~ Class:0116 Fruits',
 'CPI 2015 base ~ Class:0117 Pulses and vegetables',
 'CPI 2015 base ~ Class:0118 Sugar, jam, honey, chocolate and confectionery',
 'CPI 2015 base ~ Class:0119 Other food products',
 'CPI 2015 base ~ Class:0121 Coffee, tea and cocoa',
 'CPI 2015 base ~ Class:0122 Mineral waters, soft drinks, fruit and vegetable juices',
 'CPI 2015 base ~ Class:0211 Distilled beverages',
 'CPI 2015 base ~ Class:0212 Wine',
 'CPI 2015 base ~ Class:0213 Beer',
 'CPI 2015 base ~ Class:0220 Tobacco',
 'CPI 2015 base ~ Class:0312 Clothing',
 'CPI 2015 base ~ Class:0313 Other articles of clothing and haberdashery',
 'CPI 2015 base ~ Class:0314 Cleaning, repair and hire of clothing',
 'CPI 2015 base ~ Class:0321 Footwear',
 'CPI 2015 base ~ Class:0322 Repair and hire of footwear',
 'CPI 2015 base ~ Class:0411 Renting of main dwelling ',
 'CPI 2015 base ~ Class:0412 Other rentals',
 'CPI 2015 base ~ Class:0431 Materials for the maintenance and repair of the dwelling',
 'CPI 2015 base ~ Class:0432 Services for the maintenance and repair of the dwelling',
 'CPI 2015 base ~ Class:0441 Water supply',
 'CPI 2015 base ~ Class:0442 Refuse collection',
 'CPI 2015 base ~ Class:0443 Sewerage',
 'CPI 2015 base ~ Class:0444 Other services related to housing',
 'CPI 2015 base ~ Class:0451 Electricity',
 'CPI 2015 base ~ Class:0452 Gas',
 'CPI 2015 base ~ Class:0453 Liquid fuels',
 'CPI 2015 base ~ Class:0511 Furniture and furnishings',
 'CPI 2015 base ~ Class:0512 Carpets and other floor coverings',
 'CPI 2015 base ~ Class:0520 Household textiles',
 'CPI 2015 base ~ Class:0531 Major household appliances, electric or otherwise',
 'CPI 2015 base ~ Class:0532 Small household appliances',
 'CPI 2015 base ~ Class:0533 Repair of household appliances',
 'CPI 2015 base ~ Class:0540 Glassware, tableware and household utensils',
 'CPI 2015 base ~ Class:0551 Large tools and equipment',
 'CPI 2015 base ~ Class:0552 Small tools and accessories',
 'CPI 2015 base ~ Class:0561 Non-durable household goods',
 'CPI 2015 base ~ Class:0562 Domestic and other household services',
 'CPI 2015 base ~ Class:0611 Pharmaceutical products',
 'CPI 2015 base ~ Class:0612 Other medical products',
 'CPI 2015 base ~ Class:0613 Therapeutic appliances and equipment',
 'CPI 2015 base ~ Class:0621 Medical services',
 'CPI 2015 base ~ Class:0622 Dental services',
 'CPI 2015 base ~ Class:0623 Paramedical services',
 'CPI 2015 base ~ Class:0630 Hospital services',
 'CPI 2015 base ~ Class:0711 Motor vehicles',
 'CPI 2015 base ~ Class:0712 Motorcycles',
 'CPI 2015 base ~ Class:0713 Bicycles',
 'CPI 2015 base ~ Class:0721 Spare parts and accessories for personal vehicles',
 'CPI 2015 base ~ Class:0722 Fuels and lubricants for personal vehicles',
 'CPI 2015 base ~ Class:0723 Maintenance and repair of personal motor vehicles',
 'CPI 2015 base ~ Class:0724 Other services relating to personal motor vehicles',
 'CPI 2015 base ~ Class:0731 Passenger transport by rail',
 'CPI 2015 base ~ Class:0732 Passenger transport by road',
 'CPI 2015 base ~ Class:0733 Passenger transport by air',
 'CPI 2015 base ~ Class:0734 Passenger transport by sea and inland waterways',
 'CPI 2015 base ~ Class:0735 Combined passenger transport',
 'CPI 2015 base ~ Class:0736 Other transport services',
 'CPI 2015 base ~ Class:0810 Postal services',
 'CPI 2015 base ~ Class:0820 Telephone and facsimile equipment',
 'CPI 2015 base ~ Class:0830 Telephone and facsimile services',
 'CPI 2015 base ~ Class:0911 Equipment for the reception, recording and reproduction of sound and images',
 'CPI 2015 base ~ Class:0912 Photographic and cinematographic equipment and optical instruments',
 'CPI 2015 base ~ Class:0913 Information processing equipment',
 'CPI 2015 base ~ Class:0914 Image, sound and data media',
 'CPI 2015 base ~ Class:0922 Musical instruments and major durables for indoor entertainment',
 'CPI 2015 base ~ Class:0931 Games, toys and hobbies',
 'CPI 2015 base ~ Class:0932 Equipment for sports, camping and outdoor recreation',
 'CPI 2015 base ~ Class:0933 Gardening, plants and flowers',
 'CPI 2015 base ~ Class:0934 Pets and related products',
 'CPI 2015 base ~ Class:0935 Veterinary and other services for domestic animals',
 'CPI 2015 base ~ Class:0941 Recreational and sporting services',
 'CPI 2015 base ~ Class:0942 Cultural services',
 'CPI 2015 base ~ Class:0951 Books',
 'CPI 2015 base ~ Class:0952 Press',
 'CPI 2015 base ~ Class:0954 Stationery and drawing materials',
 'CPI 2015 base ~ Class:0960 Package tours',
 'CPI 2015 base ~ Class:1010 Pre-primary and primary education',
 'CPI 2015 base ~ Class:1020 Secondary education',
 'CPI 2015 base ~ Class:1040 Higher education',
 'CPI 2015 base ~ Class:1050 Education not defined by level',
 'CPI 2015 base ~ Class:1111 Catering',
 'CPI 2015 base ~ Class:1112 Canteens',
 'CPI 2015 base ~ Class:1120 Accommodation services',
 'CPI 2015 base ~ Class:1211 Hairdressing and beauty parlours',
 'CPI 2015 base ~ Class:1212 Electrical appliances for personal care',
 'CPI 2015 base ~ Class:1213 Other appliances, articles and products for personal care',
 'CPI 2015 base ~ Class:1231 Jewellery, costume jewellery and watches',
 'CPI 2015 base ~ Class:1232 Other personal effects',
 'CPI 2015 base ~ Class:1240 Social protection',
 'CPI 2015 base ~ Class:1252 Insurance related to housing',
 'CPI 2015 base ~ Class:1253 Health-related insurance',
 'CPI 2015 base ~ Class:1254 Transport related insurance',
 'CPI 2015 base ~ Class:1255 Other insurance',
 'CPI 2015 base ~ Class:1262 Other financial services',
 'CPI 2015 base ~ Class:1270 Other services',
 'CPI 2015 base ~ Class:General']

# Households Annual Electricity Consumption

This [dataset](https://www.ine.es/dynt3/inebase/index.htm?padre=8959&capsel=9844), part of the [2021 Population and Housing Census](https://www.ine.es/dyngs/INEbase/operacion.htm?c=Estadistica_C&cid=1254736177108&menu=resultados&idp=1254735572981#_tabs-1254736195867), provides statistical indicators of household electricity consumption in Spain at the municipal and district levels, identified by municipality and district codes and municipality name, along with the reference year. Electricity use is expressed in kilowatt-hours (kWh) and summarised through key percentiles (10th, 25th, 50th, 75th, and 90th) of the annual consumption distribution. These metrics enable the analysis of consumption patterns across different segments of households, from low- to high-usage groups. The data support comparisons between municipalities and districts, tracking spatial variations and temporal trends in household energy demand. This information is valuable for energy efficiency planning, monitoring the impact of energy policies, identifying vulnerable consumers, and developing targeted interventions to promote sustainable electricity use.

In [ ]:
elec_df = INE.AggregatedElectricityConsumption(wd=wd)

These are the geographical layers available:

In [52]:
pprint.pp(list(elec_df.keys()))

['Districts']

An example of the results for the municipality of Barcelona is the following:

In [49]:
elec_df['Districts'][elec_df['Districts']['Municipality code']=="08019"]

,Municipality code,District code,Municipality name,Percentile 10 of electricity consumption in kwh,Percentile 25 of electricity consumption in kwh,Percentile 50 of electricity consumption in kwh,Percentile 75 of electricity consumption in kwh,Percentile 90 of electricity consumption in kwh,Year
719,08019,01,Barcelona,721.0,1218.0,1942.0,3034.0,4508.0,2021
720,08019,02,Barcelona,875.0,1366.0,2075.0,3106.0,4502.0,2021
721,08019,03,Barcelona,819.0,1275.0,1928.0,2838.0,3995.0,2021
722,08019,04,Barcelona,941.0,1453.0,2179.0,3216.0,4678.0,2021
723,08019,05,Barcelona,963.0,1554.0,2443.0,3766.0,5643.0,2021
724,08019,06,Barcelona,827.0,1285.0,1954.0,2922.0,4240.0,2021
725,08019,07,Barcelona,819.0,1264.0,1901.0,2792.0,3995.0,2021
726,08019,08,Barcelona,781.0,1204.0,1804.0,2619.0,3639.0,2021
727,08019,09,Barcelona,872.0,1336.0,1985.0,2849.0,3997.0,2021
728,08019,10,Barcelona,868.0,1332.0,2010.0,2954.0,4197.0,2021

The columns available in this dataset are:

In [51]:
pprint.pp(list(elec_df['Districts'].columns), width=200)

['Municipality code',
 'District code',
 'Municipality name',
 'Percentile 10 of electricity consumption in kwh',
 'Percentile 25 of electricity consumption in kwh',
 'Percentile 50 of electricity consumption in kwh',
 'Percentile 75 of electricity consumption in kwh',
 'Percentile 90 of electricity consumption in kwh',
 'Year']

# Households Price Index

This [dataset](https://www.ine.es/dyngs/INEbase/en/operacion.htm?c=Estadistica_C&cid=1254736152838&menu=ultiDatos&idp=1254735976607) provides quarterly indicators of housing prices in Spain, broken down by autonomous community and province, identified through corresponding territorial codes and names, along with the reference year and quarter. It distinguishes between three segments: first-hand housing market (new dwellings), second-hand housing market (previously owned dwellings), and the whole housing market (combined). The indices measure price evolution over time, enabling analysis of regional and national trends in residential property values. This information is essential for monitoring real estate market dynamics, assessing housing affordability, and evaluating the impact of economic cycles and policy measures on the housing sector. The dataset supports applications in urban planning, investment analysis, and socio-economic studies related to housing supply and demand.

In [ ]:
housing_market_df = INE.HouseholdsPriceIndex(wd=wd)

These are the geographical layers available:

In [53]:
pprint.pp(list(housing_market_df.keys()))

['Province']

An example of the results for 2024-Q1 is the following:

In [55]:
housing_market_df['Province'][
    (housing_market_df['Province']["Year"]==2024) &
    (housing_market_df['Province']["Quarter"]==1)
]

,Autonomous community code,Autonomous community name,Province code,Province name,Year,Quarter,First-hand housing market,Second-hand housing market,Whole housing market
68,01,Andaluc√≠a,04,Almer√≠a,2024,1,184.535,145.362,149.880
141,01,Andaluc√≠a,11,C√°diz,2024,1,184.535,145.362,149.880
214,01,Andaluc√≠a,14,C√≥rdoba,2024,1,184.535,145.362,149.880
287,01,Andaluc√≠a,18,Granada,2024,1,184.535,145.362,149.880
360,01,Andaluc√≠a,21,Huelva,2024,1,184.535,145.362,149.880
433,01,Andaluc√≠a,23,Ja√©n,2024,1,184.535,145.362,149.880
506,01,Andaluc√≠a,29,M√°laga,2024,1,184.535,145.362,149.880
579,01,Andaluc√≠a,41,Sevilla,2024,1,184.535,145.362,149.880
652,02,Arag√≥n,22,Huesca,2024,1,163.112,138.811,143.668
725,02,Arag√≥n,44,Teruel,2024,1,163.112,138.811,143.668
798,02,Arag√≥n,50,Zaragoza,2024,1,163.112,138.811,143.668
871,03,"Asturias, Principado de",33,Asturias,2024,1,158.910,131.217,134.630
944,04,"Balears, Illes",07,"Balears, Illes",2024,1,198.151,165.377,168.273
1017,05,Canarias,35,"Palmas, Las",2024,1,175.464,147.815,149.974
1090,05,Canarias,38,Santa Cruz de Tenerife,2024,1,175.464,147.815,149.974
1163,06,Cantabria,39,Cantabria,2024,1,170.552,146.818,149.716
1236,07,Castilla y Le√≥n,05,√Åvila,2024,1,160.275,130.353,134.114
1309,07,Castilla y Le√≥n,09,Burgos,2024,1,160.275,130.353,134.114
1382,07,Castilla y Le√≥n,24,Le√≥n,2024,1,160.275,130.353,134.114
1455,07,Castilla y Le√≥n,34,Palencia,2024,1,160.275,130.353,134.114
1528,07,Castilla y Le√≥n,37,Salamanca,2024,1,160.275,130.353,134.114
1601,07,Castilla y Le√≥n,40,Segovia,2024,1,160.275,130.353,134.114
1674,07,Castilla y Le√≥n,42,Soria,2024,1,160.275,130.353,134.114
1747,07,Castilla y Le√≥n,47,Valladolid,2024,1,160.275,130.353,134.114
1820,07,Castilla y Le√≥n,49,Zamora,2024,1,160.275,130.353,134.114
1893,08,Castilla-La Mancha,02,Albacete,2024,1,150.868,118.494,123.353
1966,08,Castilla-La Mancha,13,Ciudad Real,2024,1,150.868,118.494,123.353
2039,08,Castilla-La Mancha,16,Cuenca,2024,1,150.868,118.494,123.353
2112,08,Castilla-La Mancha,19,Guadalajara,2024,1,150.868,118.494,123.353
2185,08,Castilla-La Mancha,45,Toledo,2024,1,150.868,118.494,123.353
2258,09,Catalu√±a,08,Barcelona,2024,1,190.301,159.252,162.075
2331,09,Catalu√±a,17,Girona,2024,1,190.301,159.252,162.075
2404,09,Catalu√±a,25,Lleida,2024,1,190.301,159.252,162.075
2477,09,Catalu√±a,43,Tarragona,2024,1,190.301,159.252,162.075
2550,10,Comunitat Valenciana,03,Alicante/Alacant,2024,1,169.291,136.466,140.857
2623,10,Comunitat Valenciana,12,Castell√≥n/Castell√≥,2024,1,169.291,136.466,140.857
2696,10,Comunitat Valenciana,46,Valencia/Val√®ncia,2024,1,169.291,136.466,140.857
2769,11,Extremadura,06,Badajoz,2024,1,149.546,117.762,119.938
2842,11,Extremadura,10,C√°ceres,2024,1,149.546,117.762,119.938
2915,12,Galicia,15,"Coru√±a, A",2024,1,170.540,131.011,136.417
2988,12,Galicia,27,Lugo,2024,1,170.540,131.011,136.417
3061,12,Galicia,32,Ourense,2024,1,170.540,131.011,136.417
3134,12,Galicia,36,Pontevedra,2024,1,170.540,131.011,136.417
3207,13,"Madrid, Comunidad de",28,Madrid,2024,1,187.769,164.040,168.785
3280,14,"Murcia, Regi√≥n de",30,Murcia,2024,1,172.668,132.189,136.839
3353,15,"Navarra, Comunidad Foral de",31,Navarra,2024,1,161.074,131.536,140.034
3426,16,Pa√≠s Vasco,01,Araba/√Ålava,2024,1,174.647,135.367,141.867
3499,16,Pa√≠s Vasco,48,Bizkaia,2024,1,174.647,135.367,141.867
3572,16,Pa√≠s Vasco,20,Gipuzkoa,2024,1,174.647,135.367,141.867
3645,17,"Rioja, La",26,"Rioja, La",2024,1,174.367,135.625,139.961
3718,18,Ceuta,51,Ceuta,2024,1,NaN,NaN,170.101
3791,19,Melilla,52,Melilla,2024,1,NaN,NaN,164.358
3864,NaN,NaN,NaN,NaN,2024,1,178.899,148.616,152.618

The columns available in this dataset are:

In [57]:
pprint.pp(list(housing_market_df['Province'].columns))

['Autonomous community code',
 'Autonomous community name',
 'Province code',
 'Province name',
 'Year',
 'Quarter',
 'First-hand housing market',
 'Second-hand housing market',
 'Whole housing market']

# Households Rental Price Index

This [dataset](https://www.ine.es/en/experimental/ipva/experimental_precios_vivienda_alquiler_en.htm) contains annual indicators of rental price evolution for households in Spain, disaggregated at the municipal and district levels, and identified by corresponding municipality, district, province, and country codes, along with the reference year. The Household Rental Index reflects relative changes in the cost of renting residential properties over time, allowing for spatial and temporal comparisons. The index enables the monitoring of rental market trends, identification of areas experiencing higher price pressures, and assessment of housing affordability. It is a valuable resource for policymakers, researchers, and market analysts to support housing policy development, urban planning, and socio-economic studies focused on the residential rental sector.

In [ ]:
housing_rental_df = INE.HouseholdsRentalPriceIndex(wd=wd)

These are the geographical layers available:

In [58]:
pprint.pp(list(housing_rental_df.keys()))

['Municipality', 'Districts']

An example of the results for the municipality of Barcelona is the following:

In [62]:
housing_rental_df["Districts"][housing_rental_df["Districts"]["Municipality code"]=="08019"]

,Municipality code,Year,District code,Household rental index,Country code,Province code
598,08019,2023,01,118.337,ES,08
599,08019,2022,01,114.106,ES,08
600,08019,2021,01,110.184,ES,08
601,08019,2020,01,110.636,ES,08
602,08019,2019,01,113.538,ES,08
...,...,...,...,...,...,...
723,08019,2015,10,100.000,ES,08
724,08019,2014,10,99.307,ES,08
725,08019,2013,10,99.964,ES,08
726,08019,2012,10,102.778,ES,08
727,08019,2011,10,104.278,ES,08

The columns available in this dataset are:

In [61]:
pprint.pp(list(housing_rental_df["Districts"].columns))

['Municipality code',
 'Year',
 'District code',
 'Household rental index',
 'Country code',
 'Province code']

# Essential Characteristics of Population and Households by building

This [dataset](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736177092&menu=resultados&idp=1254735572981#_tabs-1254736195788) provides highly detailed socio-demographic and housing information for the population residing in each building in Spain, obtained by extrapolating survey results to the building level. It includes characteristics of residents aged 16 and over, such as workplace/study location, commuting patterns, transport mode, domestic task participation, caregiving responsibilities, social support, digital access, and online purchasing habits. It records household composition (e.g., single-person households, cohabiting couples, number of children), housing attributes (size, number of rooms, ownership/rental regime, mortgage or rent costs, presence of a second residence), and asset ownership (vehicles, eco-friendly vehicles). Environmental and energy-related data include waste separation practices, type of heating and fuel, cooling systems, internet connection, appliances, lighting, and renewable energy installations. The dataset also captures building condition, accessibility, surrounding area problems, and availability of infrastructure or services. This rich granularity supports analyses of living conditions, housing quality, socio-economic diversity, and environmental practices at a micro-geographic scale.

In [ ]:
characteristics_buildings = INE.EssentialCharacteristicsOfPopulationAndHouseholds(
    wd=wd,
    hypercadaster_ES_input_pkl_file=f"{wd}/FromHypercadaster/08900.pkl")

The topics related to population and households are the following:

In [65]:
pprint.pp(list(characteristics_buildings.keys()), width=250)

['Personas de 16 a√±os o m√°s - Lugar de trabajo/estudio',
 'Personas de 16 a√±os o m√°s - N√∫mero de desplazamaientos',
 'Personas de 16 a√±os o m√°s - Medio de transporte',
 'Personas de 16 a√±os o m√°s - Tipo de veh√≠culo',
 'Personas de 16 a√±os o m√°s - Tiempo diario',
 'Personas de 16 a√±os o m√°s - Grado de satisfacci√≥n',
 'Personas de 16 a√±os o m√°s - Grado de participaci√≥n en las tareas dom√©sticas',
 'Personas de 16 a√±os o m√°s que conviven con otras personas - Grado de participaci√≥n en cuidados a menores o dependientes dentro del hogar',
 'Personas de 16 a√±os o m√°s que conviven con otras personas y participan en cuidados a personas dependientes dentro del hogar - Tipo de dependiente',
 'Personas de 16 a√±os o m√°s que conviven con otras personas y participan en cuidados a personas dependientes dentro del hogar - Horas diarias dedicadas al cuidado',
 'Personas de 16 a√±os o m√°s - Grado de participaci√≥n en cuidados a menores o dependientes fuera del hogar',
 'Personas de 16 a√±os o m√°s que participan en cuidados a personas dependientes fuera del hogar - Tipo de dependiente',
 'Personas de 16 a√±os o m√°s que participan en cuidados a personas dependientes fuera del hogar - Horas diarias dedicadas al cuidado',
 'Personas de 16 a√±os o m√°s - Tiene apoyo social',
 'Personas de 16 a√±os o m√°s que viven solas - Tipo de relaci√≥n',
 'Personas de 16 a√±os o m√°s que viven solas - Lugar de residencia',
 'Personas nacidas en Espa√±a - Lugar de nacimiento progenitores',
 'Personas nacidas fuera de Espa√±a - Lugar de nacimiento progenitores',
 'Personas - Residencia progenitores',
 'Personas - Nacionalidad progenitores',
 'Personas de 16 a√±os o m√°s - Nivel estudios progenitores',
 'Personas de 16 a√±os o m√°s - Accede habitualmente a internet',
 'Personas de 16 a√±os o m√°s - Dispone de perfil en alguna red social',
 'Personas de 16 a√±os o m√°s - Dispone de smartphone',
 'Personas de 16 a√±os o m√°s - Realiza compras por internet',
 'Personas de 16 a√±os o m√°s - Realiza ventas por internet',
 'Hogares de una sola persona (unipersonales) - Edad',
 'Hogares de una sola persona (unipersonales) - Nacionalidad',
 'Hogares de una sola persona (unipersonales) - Estado civil',
 'Hogares de una sola persona (unipersonales) - Nivel educativo',
 'Hogares de una sola persona (unipersonales) - Situaci√≥n laboral',
 'Hogares de una sola persona (unipersonales) - Nivel de ingresos mensuales netos del hogar',
 'Parejas convivientes - Sexo de la pareja',
 'Parejas convivientes - Nacionalidad de la pareja',
 'Parejas convivientes - N√∫mero de hijos',
 'Hogares - N√∫mero de hijos',
 'Hogares - N√∫mero de habitaciones de la vivienda',
 'Hogares - Superficie √∫til de la vivienda',
 'Hogares - Tipo de edificio',
 'Hogares - R√©gimen de tenencia de la vivienda',
 'Hogares/personas - R√©gimen de tenencia de la vivienda',
 'Hogares/personas en viviendas alquiladas - Cuota mensual del alquiler',
 'Hogares/personas en viviendas propias, - Cuota mensual de la hipoteca',
 'Hogares/personas - Disponen de segunda residencia',
 'Hogares - Disponen de segunda residencia',
 'Hogares/personas con segunda residencia - Lugar de la segunda residencia',
 'Hogares/personas con segunda residencia - D√≠as de uso de la segunda residencia al a√±o',
 'Hogares/personas - N√∫mero de veh√≠culos',
 'Hogares - N√∫mero de veh√≠culos',
 'Hogares/personas con veh√≠culo - Veh√≠culo ec√≥logico',
 'Hogares con veh√≠culo - Veh√≠culo ec√≥logico',
 'Hogares/personas - Separan alg√∫n tipo de residuo',
 'Hogares - Separan alg√∫n tipo de residuo',
 'Hogares - Tipo de residuos separados',
 'Hogares/personas con servicio dom√©stico remunerado - Servicio dom√©stico remunerado',
 'Hogares con servicio dom√©stico remunerado - Servicio dom√©stico remunerado',
 'Hogares/personas con ayuda externa - Ayuda externa',
 'Hogares con ayuda externa - Ayuda externa',
 'Viviendas principales - Adaptada a necesidades propias del envejecimiento',
 'Viviendas principales - Problema de aislamiento',
 'Viviendas principales - Tipo de calefacci√≥n',
 'Viviendas principales con calefacci√≥n - Tipo de combustible',
 'Viviendas principales - Sistema de suministro de agua',
 'Viviendas principales - Tiene sistema de refrigeraci√≥n',
 'Viviendas principales - Tipo de conexi√≥n a internet',
 'Viviendas principales - Tipo de electrodom√©stico',
 'Viviendas principales - Tipo de bombillas',
 'Viviendas principales - Superficie √∫til de la vivienda',
 'Viviendas principales - Aseo con inodoro / Ba√±era o ducha',
 'Viviendas principales - N√∫mero de cuartos de ba√±o o aseos',
 'Viviendas principales - Cocina independiente de 4 m2 o m√°s',
 'Viviendas principales - N√∫mero de habitaciones',
 'Viviendas principales - Tipo de problem√°tica en la zona',
 'Viviendas principales - Tipo de infraestructura o servicio',
 'Viviendas principales - Estado de conservaci√≥n',
 'Viviendas principales - Accesibilidad',
 'Viviendas principales - Tipo de instalaci√≥n',
 'Viviendas principales - N√∫mero de plazas de garaje',
 'Viviendas principales - Tipo de dispositivo de energ√≠a renovable']

As an example, in the case of households' surrounding area problems, the following columns are available:

In [33]:
characteristics_buildings['Viviendas principales - Tipo de problem√°tica en la zona']

,Viviendas principales - Tipo de problem√°tica en la zona ~ Contaminaci√≥n o malos olores (%),Viviendas principales - Tipo de problem√°tica en la zona ~ Delincuencia (%),Viviendas principales - Tipo de problem√°tica en la zona ~ Malas comunicaciones (%),Viviendas principales - Tipo de problem√°tica en la zona ~ Molestias relacionadas con actividades tur√≠sticas o locales de hosteler√≠a (%),Viviendas principales - Tipo de problem√°tica en la zona ~ Poca limpieza en las calles (%),Viviendas principales - Tipo de problem√°tica en la zona ~ Pocas zonas verdes (%),Viviendas principales - Tipo de problem√°tica en la zona ~ Ruidos exteriores (%)
building_reference,,,,,,,
0475807DF3807E,13.491540,18.477356,8.089040,9.409235,16.495467,12.036912,22.000450
0475106DF3807E,13.491540,18.477356,8.089040,9.409235,16.495467,12.036912,22.000450
0475806DF3807E,13.491540,18.477356,8.089040,9.409235,16.495467,12.036912,22.000450
0475107DF3807E,13.491540,18.477356,8.089040,9.409235,16.495467,12.036912,22.000450
2483117DF3828C,15.361785,16.009413,2.852117,10.104544,16.859097,14.034775,24.778269
...,...,...,...,...,...,...,...
9972401DF2897D,15.220475,15.752335,2.904919,9.974243,16.831416,14.426390,24.890221
9972404DF2897D,15.220475,15.752335,2.904919,9.974243,16.831416,14.426390,24.890221
9973909DF2897D,14.732590,16.671850,3.396563,10.337110,17.067403,14.159384,23.635101
9975601DF2897F,15.204432,15.767740,2.903412,9.968769,16.836048,14.427268,24.892331
9978522DF2897H,14.917014,16.865942,3.352328,10.482376,17.053874,13.790576,23.537889

In [64]:
pprint.pp(list(characteristics_buildings['Viviendas principales - Tipo de problem√°tica en la zona']),width=200)

['Viviendas principales - Tipo de problem√°tica en la zona ~ Contaminaci√≥n o malos olores (%)',
 'Viviendas principales - Tipo de problem√°tica en la zona ~ Delincuencia (%)',
 'Viviendas principales - Tipo de problem√°tica en la zona ~ Malas comunicaciones (%)',
 'Viviendas principales - Tipo de problem√°tica en la zona ~ Molestias relacionadas con actividades tur√≠sticas o locales de hosteler√≠a (%)',
 'Viviendas principales - Tipo de problem√°tica en la zona ~ Poca limpieza en las calles (%)',
 'Viviendas principales - Tipo de problem√°tica en la zona ~ Pocas zonas verdes (%)',
 'Viviendas principales - Tipo de problem√°tica en la zona ~ Ruidos exteriores (%)']

Whereas, in the case of households' conservation status, the following columns are available:

In [68]:
characteristics_buildings['Viviendas principales - Estado de conservaci√≥n']

,Viviendas principales - Estado de conservaci√≥n ~ Bueno,Viviendas principales - Estado de conservaci√≥n ~ Excelente,Viviendas principales - Estado de conservaci√≥n ~ Malo,Viviendas principales - Estado de conservaci√≥n ~ Muy bueno,Viviendas principales - Estado de conservaci√≥n ~ Normal,Viviendas principales - Estado de conservaci√≥n ~ Regular
building_reference,,,,,,
0475807DF3807E,31.851407,11.364060,4.048376,10.393323,27.062165,15.280668
0475106DF3807E,31.851407,11.364060,4.048376,10.393323,27.062165,15.280668
0475806DF3807E,31.851407,11.364060,4.048376,10.393323,27.062165,15.280668
0475107DF3807E,31.851407,11.364060,4.048376,10.393323,27.062165,15.280668
2483117DF3828C,31.088809,5.500753,3.291270,13.401670,27.897534,18.819963
...,...,...,...,...,...,...
9972401DF2897D,31.258783,5.168294,2.905059,14.183478,28.433202,18.051183
9972404DF2897D,31.258783,5.168294,2.905059,14.183478,28.433202,18.051183
9973909DF2897D,32.071576,7.713117,1.891269,17.166608,24.317443,16.839986
9975601DF2897F,31.249614,5.167727,2.907458,14.206171,28.422721,18.046310
9978522DF2897H,31.882330,8.010168,2.557237,16.339886,23.762184,17.448195

In [66]:
pprint.pp(list(characteristics_buildings['Viviendas principales - Estado de conservaci√≥n']),width=200)

['Viviendas principales - Estado de conservaci√≥n ~ Bueno',
 'Viviendas principales - Estado de conservaci√≥n ~ Excelente',
 'Viviendas principales - Estado de conservaci√≥n ~ Malo',
 'Viviendas principales - Estado de conservaci√≥n ~ Muy bueno',
 'Viviendas principales - Estado de conservaci√≥n ~ Normal',
 'Viviendas principales - Estado de conservaci√≥n ~ Regular']